export const HOME = '/'
export const HOME_RESEARCHERS_LIST = '/researchers-list'
export const RESEARCHER = '/researchers/:address'
export const PACKAGE_ITEM = '/packages/:id/:version'
export const BETA_SIGNUP = '/beta-signup'
